# Generated by Django 3.2 on 2023-02-01 08:43

import application_info.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to=application_info.models.Post.img_upload)),
                ('short_text', models.TextField(blank=True, verbose_name='Короткий текст')),
                ('article', models.TextField(blank=True)),
                ('publication_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_faq', models.BooleanField(default=False)),
                ('is_notify', models.BooleanField(default=False)),
                ('is_news', models.BooleanField(default=False)),
                ('saw_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='PostTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(default=5, editable=False, validators=[django.core.validators.MaxValueValidator(5, message='Оценка не может быть больше 5'), django.core.validators.MinValueValidator(1, message='Оценка не может быть меньше 1')])),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(max_length=10)),
                ('version_suffix', models.CharField(max_length=10)),
                ('is_actual', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=application_info.models.ReviewImg.img_upload)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_info.review')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='PostImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=application_info.models.PostImg.img_upload)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_info.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_info.posttopic'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('system', 'Система'), ('recalculates', 'Пересчеты'), ('accounts', 'Аккаунты'), ('application_info', 'Информация о приложении'), ('statistic', 'Статистика')], default='system', max_length=30)),
                ('action', models.CharField(max_length=100)),
                ('is_error', models.BooleanField(default=False)),
                ('static_user_id', models.CharField(blank=True, max_length=36)),
                ('user_email', models.CharField(blank=True, max_length=250)),
                ('user_name', models.CharField(blank=True, max_length=250)),
                ('log', models.TextField()),
                ('system_version', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('topic', 'name')},
        ),
    ]
