# Generated by Django 3.2 on 2023-02-01 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import searching.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorsEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('code', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategoryProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='searching.equipmentcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategoryPropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='searching.equipmentcategoryproperty')),
            ],
            options={
                'ordering': ['property'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_models', to='searching.equipmentcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OurEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(db_index=True, max_length=250, unique=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('comment', models.TextField(default='', null=True)),
                ('is_promotion', models.BooleanField(default=False)),
                ('is_not_actual', models.BooleanField(default=False)),
                ('promotion_description', models.TextField(blank=True, default='', null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='our_equipment', to='searching.equipmentcategory')),
                ('model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='searching.equipmentmodel')),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='searching.equipmentunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(default=None, null=True)),
                ('psp', models.IntegerField(default=80)),
                ('is_active', models.BooleanField(default=True)),
                ('is_success', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('is_interrupted', models.BooleanField(default=False)),
                ('rows_count', models.IntegerField(default=0)),
                ('match_rows_count', models.IntegerField(default=0)),
                ('unmatch_rows_count', models.IntegerField(default=0)),
                ('skip_rows_count', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='SearchProcessResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_code', models.TextField(blank=True)),
                ('input_name', models.TextField(blank=True)),
                ('output_code', models.TextField(blank=True)),
                ('output_name', models.TextField(blank=True)),
                ('is_match', models.BooleanField(default=False)),
                ('is_unmatch', models.BooleanField(default=False)),
                ('is_skip', models.BooleanField(default=False)),
                ('match_in_own_codes', models.BooleanField(default=False)),
                ('match_in_own_names', models.BooleanField(default=False)),
                ('match_in_comp_codes', models.BooleanField(default=False)),
                ('match_in_comp_names', models.BooleanField(default=False)),
                ('match_in_keys', models.BooleanField(default=False)),
                ('match_by_properties', models.BooleanField(default=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='searching.searchprocess')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OurEquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, null=True, upload_to=searching.models.OurEquipmentImage.img_upload)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='searching.ourequipment')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('comp_equipment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='searching.competitorsequipment')),
                ('our_equipment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='searching.ourequipment')),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.AddField(
            model_name='competitorsequipment',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_equipment', to='searching.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='competitorsequipment',
            name='competitor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='searching.competitor'),
        ),
        migrations.AddField(
            model_name='competitorsequipment',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='searching.equipmentunit'),
        ),
        migrations.CreateModel(
            name='OurEquipmentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='searching.ourequipment')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_equipment_properties', to='searching.equipmentcategoryproperty')),
                ('value', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='our_equipment_values', to='searching.equipmentcategorypropertyvalue')),
            ],
            options={
                'ordering': ['equipment'],
                'unique_together': {('equipment', 'property', 'value')},
            },
        ),
        migrations.CreateModel(
            name='CompetitorsEquipmentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='searching.competitorsequipment')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_equipment_properties', to='searching.equipmentcategoryproperty')),
                ('value', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_equipment_values', to='searching.equipmentcategorypropertyvalue')),
            ],
            options={
                'ordering': ['property'],
                'unique_together': {('equipment', 'property', 'value')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='competitorsequipment',
            unique_together={('competitor', 'code')},
        ),
    ]
